/**
 * Каталог услуг и отделений Соцфонда КР (демо).
 * Сюда можно добавлять новые услуги и филиалы.
 */
(function (global) {
  /** Группы услуг для выпадающих списков */
  var BOOKING_SERVICE_GROUPS = [
    {
      groupKey: 'svc_grp_pension',
      services: [
        'pension',
        'pension_age',
        'pension_disability',
        'pension_survivor',
        'pension_social',
        'pension_recalc',
      ],
    },
    {
      groupKey: 'svc_grp_benefit',
      services: [
        'benefit',
        'benefit_family',
        'benefit_child',
        'benefit_maternity',
        'benefit_funeral',
        'benefit_unemployment',
        'benefit_temp_disability',
      ],
    },
    {
      groupKey: 'svc_grp_certificate',
      services: ['certificate', 'cert_pension_size', 'cert_work_period', 'cert_income_state'],
    },
    {
      groupKey: 'svc_grp_other',
      services: ['consult', 'experience', 'savings', 'registration', 'appeal'],
    },
  ];

  /** Отделения по регионам Кыргызстана */
  var BOOKING_OFFICE_REGIONS = [
    {
      regionKey: 'region_bishkek',
      offices: ['bishkek_center', 'bishkek_oktyabr', 'bishkek_leninsky'],
    },
    {
      regionKey: 'region_chuy',
      offices: ['tokmok', 'kant', 'kara_balta', 'shopokov'],
    },
    {
      regionKey: 'region_osh_city',
      offices: ['osh_city'],
    },
    {
      regionKey: 'region_osh',
      offices: ['uzgen', 'kara_suu', 'gulcha', 'nookat'],
    },
    {
      regionKey: 'region_jalal',
      offices: ['jalal_abad', 'mailuu_suu', 'toktogul', 'kerben', 'kochkor_ata'],
    },
    {
      regionKey: 'region_naryn',
      offices: ['naryn', 'at_bashy'],
    },
    {
      regionKey: 'region_issyk_kul',
      offices: ['karakol', 'balykchy', 'cholpon_ata', 'tyup'],
    },
    {
      regionKey: 'region_talas',
      offices: ['talas', 'talas_kirovka', 'talas_manas', 'talas_pokrovka', 'talas_kyzyl_adyr', 'talas_bakay_ata'],
    },
    {
      regionKey: 'region_batken',
      offices: ['batken', 'kyzyl_kiya', 'isfana', 'sulukta'],
    },
  ];

  var OFFICE_LEGACY = {
    bishkek: 'bishkek_center',
    osh: 'osh_city',
    jalal: 'jalal_abad',
  };

  var WIZARD_SERVICE_ALIAS = {
    pension_age: 'pension',
    pension_disability: 'pension',
    pension_survivor: 'pension',
    pension_social: 'pension',
    pension_recalc: 'pension',
    benefit_family: 'benefit',
    benefit_child: 'benefit',
    benefit_maternity: 'benefit',
    benefit_funeral: 'benefit',
    benefit_unemployment: 'benefit',
    benefit_temp_disability: 'benefit',
    cert_pension_size: 'certificate',
    cert_work_period: 'certificate',
    cert_income_state: 'certificate',
    experience: 'pension',
    savings: 'consult',
    registration: 'consult',
    appeal: 'consult',
  };

  var BOOKING_STAFF_ALIAS = {
    pension_age: 'pension',
    pension_disability: 'pension',
    pension_survivor: 'pension',
    pension_social: 'pension',
    pension_recalc: 'pension',
    benefit_family: 'benefit',
    benefit_child: 'benefit',
    benefit_maternity: 'benefit',
    benefit_funeral: 'benefit',
    benefit_unemployment: 'benefit',
    benefit_temp_disability: 'benefit',
    cert_pension_size: 'certificate',
    cert_work_period: 'certificate',
    cert_income_state: 'certificate',
    experience: 'pension',
    savings: 'consult',
    registration: 'consult',
    appeal: 'consult',
  };

  var BOOKING_SUBTYPE_EXTRA = {
    pension_age: ['sub_pension_first', 'sub_pension_recalc'],
    pension_disability: ['sub_pension_first', 'sub_pension_recalc'],
    pension_survivor: ['sub_pension_first'],
    pension_social: ['sub_pension_first'],
    pension_recalc: ['sub_pension_recalc', 'sub_pension_transfer'],
    benefit_family: ['sub_benefit_family'],
    benefit_child: ['sub_benefit_child'],
    benefit_maternity: ['sub_benefit_maternity'],
    benefit_funeral: ['sub_benefit_funeral'],
    benefit_unemployment: ['sub_benefit_unemployment'],
    benefit_temp_disability: ['sub_benefit_temp_disability'],
    cert_pension_size: ['sub_cert_pension'],
    cert_work_period: ['sub_cert_work'],
    cert_income_state: ['sub_cert_income'],
    experience: ['sub_exp_transfer', 'sub_exp_restore', 'sub_exp_confirm'],
    savings: ['sub_savings_balance', 'sub_savings_statement'],
    registration: ['sub_reg_insured', 'sub_reg_employer'],
    appeal: ['sub_appeal_decision', 'sub_appeal_payment'],
  };

  var BOOKING_CATALOG_I18N = {
    ru: {
      svc_grp_pension: 'Пенсии',
      svc_grp_benefit: 'Пособия и выплаты',
      svc_grp_certificate: 'Справки и выписки',
      svc_grp_other: 'Прочие услуги',
      region_bishkek: 'г. Бишкек',
      region_chuy: 'Чуйская область',
      region_osh_city: 'г. Ош',
      region_osh: 'Ошская область',
      region_jalal: 'Жалал-Абадская область',
      region_naryn: 'Нарынская область',
      region_issyk_kul: 'Иссык-Кульская область',
      region_talas: 'Таласская область',
      region_batken: 'Баткенская область',
      region_unknown: 'Регион не указан',
      svc_pension: 'Пенсия (общее обращение)',
      svc_pension_age: 'Пенсия по возрасту',
      svc_pension_disability: 'Пенсия по инвалидности',
      svc_pension_survivor: 'Пенсия по потере кормильца',
      svc_pension_social: 'Социальная пенсия',
      svc_pension_recalc: 'Перерасчёт пенсии',
      svc_benefit: 'Пособие (общее обращение)',
      svc_benefit_family: 'Пособие «Семейная помощь»',
      svc_benefit_child: 'Пособие по уходу за ребёнком',
      svc_benefit_maternity: 'Пособие по беременности и родам',
      svc_benefit_funeral: 'Пособие на погребение',
      svc_benefit_unemployment: 'Пособие по безработице',
      svc_benefit_temp_disability: 'Пособие по временной нетрудоспособности',
      svc_certificate: 'Справка (общее обращение)',
      svc_cert_pension_size: 'Справка о размере пенсии',
      svc_cert_work_period: 'Справка о трудовом стаже',
      svc_cert_income_state: 'Справка о доходах для пособия',
      svc_consult: 'Консультация',
      svc_experience: 'Учёт и перенос стажа',
      svc_savings: 'Пенсионные накопления',
      svc_registration: 'Регистрация в системе соцстрахования',
      svc_appeal: 'Обжалование решения Соцфонда',
      office_bishkek_center: 'г. Бишкек, ул. Московская 66 (центральное)',
      office_bishkek_oktyabr: 'г. Бишкек, Октябрьский район',
      office_bishkek_leninsky: 'г. Бишкек, Ленинский район',
      office_tokmok: 'г. Токмок, Чуйская обл.',
      office_kant: 'г. Кант, Чуйская обл.',
      office_kara_balta: 'г. Кара-Балта, Чуйская обл.',
      office_shopokov: 'г. Шопоков, Чуйская обл.',
      office_osh_city: 'г. Ош, ул. Ленина (главное отделение)',
      office_uzgen: 'г. Узген, Ошская обл.',
      office_kara_suu: 'г. Кара-Суу, Ошская обл.',
      office_gulcha: 'с. Гульча, Ошская обл.',
      office_nookat: 'г. Ноокат, Ошская обл.',
      office_jalal_abad: 'г. Джалал-Абад',
      office_mailuu_suu: 'г. Майли-Суу, Жалал-Абадская обл.',
      office_toktogul: 'г. Токтогул, Жалал-Абадская обл.',
      office_kerben: 'г. Кербен, Жалал-Абадская обл.',
      office_kochkor_ata: 'г. Кочкор-Ата, Жалал-Абадская обл.',
      office_naryn: 'г. Нарын, Нарынская обл.',
      office_at_bashy: 'г. Ат-Башы, Нарынская обл.',
      office_karakol: 'г. Каракол, Иссык-Кульская обл.',
      office_balykchy: 'г. Балыкчи, Иссык-Кульская обл.',
      office_cholpon_ata: 'г. Чолпон-Ата, Иссык-Кульская обл.',
      office_tyup: 'с. Тюп, Иссык-Кульская обл.',
      office_talas: 'г. Талас, ул. Ленина 187 (областное отделение)',
      office_talas_kirovka: 'г. Кировка, Таласская обл.',
      office_talas_manas: 'с. Манас, Таласская обл.',
      office_talas_pokrovka: 'с. Покровка, Таласская обл.',
      office_talas_kyzyl_adyr: 'с. Кызыл-Адыр, Таласская обл.',
      office_talas_bakay_ata: 'с. Бакай-Ата, Таласская обл.',
      office_batken: 'г. Баткен, Баткенская обл.',
      office_kyzyl_kiya: 'г. Кызыл-Кия, Баткенская обл.',
      office_isfana: 'г. Исфана, Баткенская обл.',
      office_sulukta: 'г. Сулюкта, Баткенская обл.',
      office_bishkek: 'Центральное отделение (Бишкек)',
      office_osh: 'Ошское отделение',
      office_jalal: 'Джалал-Абадское отделение',
      sub_benefit_maternity: 'Пособие по беременности и родам',
      sub_benefit_funeral: 'Пособие на погребение',
      sub_benefit_temp_disability: 'Временная нетрудоспособность',
      sub_exp_transfer: 'Перенос стажа из другой страны',
      sub_exp_restore: 'Восстановление стажа',
      sub_exp_confirm: 'Подтверждение периодов работы',
      sub_savings_balance: 'Справка о накоплениях',
      sub_savings_statement: 'Выписка по лицевому счёту',
      sub_reg_insured: 'Регистрация застрахованного лица',
      sub_reg_employer: 'Регистрация работодателя',
      sub_appeal_decision: 'Обжалование отказа',
      sub_appeal_payment: 'Обжалование размера выплаты',
      ai_services_list:
        'Услуги: пенсии (по возрасту, инвалидности, потере кормильца, социальная, перерасчёт), пособия (семейная помощь, детям, беременность, погребение, безработица), справки, учёт стажа, накопления, консультация, обжалование. Отделения — во всех областях КР (раздел «Запись»).',
    },
    ky: {
      svc_grp_pension: 'Пенсиялар',
      svc_grp_benefit: 'Жөлөмдөр жана төлөмдөр',
      svc_grp_certificate: 'Маалыматтар жана көчүрмөлөр',
      svc_grp_other: 'Башка кызматтар',
      region_bishkek: 'Бишкек ш.',
      region_chuy: 'Чүй облусу',
      region_osh_city: 'Ош ш.',
      region_osh: 'Ош облусу',
      region_jalal: 'Жалал-Абад облусу',
      region_naryn: 'Нарын облусу',
      region_issyk_kul: 'Ысык-Көл облусу',
      region_talas: 'Талас облусу',
      region_batken: 'Баткен облусу',
      region_unknown: 'Аймак көрсөтүлгөн эмес',
      svc_pension: 'Пенсия (жалпы кайрылуу)',
      svc_pension_age: 'Жаш боюнча пенсия',
      svc_pension_disability: 'Майыптык боюнча пенсия',
      svc_pension_survivor: 'Тарбиялоочуну жоготуу боюнча пенсия',
      svc_pension_social: 'Социалдык пенсия',
      svc_pension_recalc: 'Пенсияны кайра эсептөө',
      svc_benefit: 'Жөлөм (жалпы кайрылуу)',
      svc_benefit_family: '«Үй-бүлөлүк жардам» жөлөмү',
      svc_benefit_child: 'Бала багуу жөлөмү',
      svc_benefit_maternity: 'Боюнда жана боштогондук жөлөмү',
      svc_benefit_funeral: 'Жерге коюу жөлөмү',
      svc_benefit_unemployment: 'Жумушсуздук жөлөмү',
      svc_benefit_temp_disability: 'Убактылуу эмгекке жарамсыздык жөлөмү',
      svc_certificate: 'Маалымат (жалпы)',
      svc_cert_pension_size: 'Пенсиянын өлчөмү жөнүндө маалымат',
      svc_cert_work_period: 'Эмгек стажы жөнүндө маалымат',
      svc_cert_income_state: 'Жөлөм үчүн киреше жөнүндө маалымат',
      svc_consult: 'Кеңеш',
      svc_experience: 'Стажды эсепке алуу жана которуу',
      svc_savings: 'Пенсиялык жыйноолор',
      svc_registration: 'Соцкамсыздандыруу системасында каттоо',
      svc_appeal: 'Соцфонд чечимине каршы доо',
      office_bishkek_center: 'Бишкек ш., Москва көч. 66 (борбордук)',
      office_bishkek_oktyabr: 'Бишкек ш., Октябрь району',
      office_bishkek_leninsky: 'Бишкек ш., Ленин району',
      office_tokmok: 'Токмок ш., Чүй обл.',
      office_kant: 'Кант ш., Чүй обл.',
      office_kara_balta: 'Кара-Балта ш., Чүй обл.',
      office_shopokov: 'Шопоков ш., Чүй обл.',
      office_osh_city: 'Ош ш., Ленин көч. (башкы бөлүм)',
      office_uzgen: 'Өзгөн ш., Ош обл.',
      office_kara_suu: 'Кара-Суу ш., Ош обл.',
      office_gulcha: 'Гүлчө айылы, Ош обл.',
      office_nookat: 'Ноокат ш., Ош обл.',
      office_jalal_abad: 'Жалал-Абад ш.',
      office_mailuu_suu: 'Майлуу-Суу ш., Жалал-Абад обл.',
      office_toktogul: 'Токтогул ш., Жалал-Абад обл.',
      office_kerben: 'Кербен ш., Жалал-Абад обл.',
      office_kochkor_ata: 'Кочкор-Ата ш., Жалал-Абад обл.',
      office_naryn: 'Нарын ш., Нарын обл.',
      office_at_bashy: 'Ат-Башы ш., Нарын обл.',
      office_karakol: 'Каракол ш., Ысык-Көл обл.',
      office_balykchy: 'Балыкчы ш., Ысык-Көл обл.',
      office_cholpon_ata: 'Чолпон-Ата ш., Ысык-Көл обл.',
      office_tyup: 'Түп айылы, Ысык-Көл обл.',
      office_talas: 'Талас ш., Ленин көч. 187 (облустук бөлүм)',
      office_talas_kirovka: 'Кировка ш., Талас обл.',
      office_talas_manas: 'Манас айылы, Талас обл.',
      office_talas_pokrovka: 'Покровка айылы, Талас обл.',
      office_talas_kyzyl_adyr: 'Кызыл-Адыр айылы, Талас обл.',
      office_talas_bakay_ata: 'Бакай-Ата айылы, Талас обл.',
      office_batken: 'Баткен ш., Баткен обл.',
      office_kyzyl_kiya: 'Кызыл-Кыя ш., Баткен обл.',
      office_isfana: 'Исфана ш., Баткен обл.',
      office_sulukta: 'Сүлүктү ш., Баткен обл.',
      office_bishkek: 'Борбордук бөлүм (Бишкек)',
      office_osh: 'Ош бөлүмү',
      office_jalal: 'Жалал-Абад бөлүмү',
      sub_benefit_maternity: 'Боюнда жана боштогондук жөлөмү',
      sub_benefit_funeral: 'Жерге коюу жөлөмү',
      sub_benefit_temp_disability: 'Убактылуу эмгекке жарамсыздык',
      sub_exp_transfer: 'Стажды башка өлкөдөн которуу',
      sub_exp_restore: 'Стажды калыбына келтирүү',
      sub_exp_confirm: 'Иш мезгилдерин ырастоо',
      sub_savings_balance: 'Жыйноолор жөнүндө маалымат',
      sub_savings_statement: 'Эсеп боюнча көчүрмө',
      sub_reg_insured: 'Камсыздандырылган жактын каттоосу',
      sub_reg_employer: 'Иш берүүчүнүн каттоосу',
      sub_appeal_decision: 'Баш тартууну каршы доо',
      sub_appeal_payment: 'Төлөм өлчөмүн каршы доо',
      ai_services_list:
        'Кызматтар: пенсиялар, жөлөмдөр, маалыматтар, стаж, жыйноолор, каттоо, кеңеш, доо. Бөлүмдөр КРдын бардык облустарында ( «Жазылуу» бөлүмү).',
    },
    en: {
      svc_grp_pension: 'Pensions',
      svc_grp_benefit: 'Benefits and payments',
      svc_grp_certificate: 'Certificates',
      svc_grp_other: 'Other services',
      region_bishkek: 'Bishkek city',
      region_chuy: 'Chuy region',
      region_osh_city: 'Osh city',
      region_osh: 'Osh region',
      region_jalal: 'Jalal-Abad region',
      region_naryn: 'Naryn region',
      region_issyk_kul: 'Issyk-Kul region',
      region_talas: 'Talas region',
      region_batken: 'Batken region',
      region_unknown: 'Region not specified',
      svc_pension: 'Pension (general)',
      svc_pension_age: 'Old-age pension',
      svc_pension_disability: 'Disability pension',
      svc_pension_survivor: 'Survivor pension',
      svc_pension_social: 'Social pension',
      svc_pension_recalc: 'Pension recalculation',
      svc_benefit: 'Benefit (general)',
      svc_benefit_family: 'Family support benefit',
      svc_benefit_child: 'Childcare benefit',
      svc_benefit_maternity: 'Maternity benefit',
      svc_benefit_funeral: 'Funeral benefit',
      svc_benefit_unemployment: 'Unemployment benefit',
      svc_benefit_temp_disability: 'Temporary disability benefit',
      svc_certificate: 'Certificate (general)',
      svc_cert_pension_size: 'Pension amount certificate',
      svc_cert_work_period: 'Work history certificate',
      svc_cert_income_state: 'Income certificate for benefits',
      svc_consult: 'Consultation',
      svc_experience: 'Work experience registration/transfer',
      svc_savings: 'Pension savings',
      svc_registration: 'Social insurance registration',
      svc_appeal: 'Appeal of Social Fund decision',
      office_bishkek_center: 'Bishkek, 66 Moskovskaya St. (central)',
      office_bishkek_oktyabr: 'Bishkek, Oktyabrsky district',
      office_bishkek_leninsky: 'Bishkek, Leninsky district',
      office_tokmok: 'Tokmok, Chuy region',
      office_kant: 'Kant, Chuy region',
      office_kara_balta: 'Kara-Balta, Chuy region',
      office_shopokov: 'Shopokov, Chuy region',
      office_osh_city: 'Osh, Lenin St. (main office)',
      office_uzgen: 'Uzgen, Osh region',
      office_kara_suu: 'Kara-Suu, Osh region',
      office_gulcha: 'Gulcha village, Osh region',
      office_nookat: 'Nookat, Osh region',
      office_jalal_abad: 'Jalal-Abad city',
      office_mailuu_suu: 'Mailuu-Suu, Jalal-Abad region',
      office_toktogul: 'Toktogul, Jalal-Abad region',
      office_kerben: 'Kerben, Jalal-Abad region',
      office_kochkor_ata: 'Kochkor-Ata, Jalal-Abad region',
      office_naryn: 'Naryn, Naryn region',
      office_at_bashy: 'At-Bashy, Naryn region',
      office_karakol: 'Karakol, Issyk-Kul region',
      office_balykchy: 'Balykchy, Issyk-Kul region',
      office_cholpon_ata: 'Cholpon-Ata, Issyk-Kul region',
      office_tyup: 'Tyup village, Issyk-Kul region',
      office_talas: 'Talas city, 187 Lenin St. (regional office)',
      office_talas_kirovka: 'Kirovka, Talas region',
      office_talas_manas: 'Manas village, Talas region',
      office_talas_pokrovka: 'Pokrovka village, Talas region',
      office_talas_kyzyl_adyr: 'Kyzyl-Adyr village, Talas region',
      office_talas_bakay_ata: 'Bakay-Ata village, Talas region',
      office_batken: 'Batken, Batken region',
      office_kyzyl_kiya: 'Kyzyl-Kiya, Batken region',
      office_isfana: 'Isfana, Batken region',
      office_sulukta: 'Sulukta, Batken region',
      office_bishkek: 'Central office (Bishkek)',
      office_osh: 'Osh office',
      office_jalal: 'Jalal-Abad office',
      sub_benefit_maternity: 'Maternity benefit',
      sub_benefit_funeral: 'Funeral benefit',
      sub_benefit_temp_disability: 'Temporary disability',
      sub_exp_transfer: 'Transfer experience from abroad',
      sub_exp_restore: 'Restore work record',
      sub_exp_confirm: 'Confirm employment periods',
      sub_savings_balance: 'Savings statement',
      sub_savings_statement: 'Account statement',
      sub_reg_insured: 'Insured person registration',
      sub_reg_employer: 'Employer registration',
      sub_appeal_decision: 'Appeal refusal',
      sub_appeal_payment: 'Appeal payment amount',
      ai_services_list:
        'Services: pensions (age, disability, survivor, social, recalculation), benefits (family, child, maternity, funeral, unemployment), certificates, experience, savings, registration, consultation, appeal. Offices in all regions of the KR (Booking section).',
    },
  };

  global.SocFondBookingCatalog = {
    BOOKING_SERVICE_GROUPS: BOOKING_SERVICE_GROUPS,
    BOOKING_OFFICE_REGIONS: BOOKING_OFFICE_REGIONS,
    OFFICE_LEGACY: OFFICE_LEGACY,
    WIZARD_SERVICE_ALIAS: WIZARD_SERVICE_ALIAS,
    BOOKING_STAFF_ALIAS: BOOKING_STAFF_ALIAS,
    BOOKING_SUBTYPE_EXTRA: BOOKING_SUBTYPE_EXTRA,
    BOOKING_CATALOG_I18N: BOOKING_CATALOG_I18N,
    allServiceKeys: function () {
      var keys = [];
      BOOKING_SERVICE_GROUPS.forEach(function (g) {
        g.services.forEach(function (k) {
          if (keys.indexOf(k) === -1) keys.push(k);
        });
      });
      return keys;
    },
  };
})(typeof window !== 'undefined' ? window : global);
